title: Aivars Kalvāns
tagline: Tinkering with Oracle Tuxedo and other software
description: Tinkering with Oracle Tuxedo and other software
url: http://aivarsk.com
paginate: 1
baseurl: ""
permalink: pretty

sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aivars Kalvāns
  url:               http://aivarsk.com
  email:             aivars.kalvans@gmail.com

social:
  name: Aivars Kalvāns
  links:
    - https://github.com/aivarsk
    - https://www.linkedin.com/in/aivarsk
    - https://stackoverflow.com/story/aivarsk
    - https://twitter.com/aivarskalvans

plugins:
  - jekyll-paginate
  - jekyll-seo-tag


collections:
  tags:
    output: true
    permalink: tag/:path/
