title: Aivars Kalvāns
tagline: Tinkering with Oracle Tuxedo and other software
description: Tinkering with Oracle Tuxedo and other software
url: http://aivarsk.com
paginate: 1
baseurl: ""
permalink: pretty

sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aivars Kalvāns
  url:               http://aivarsk.com
  email:             aivars.kalvans@gmail.com

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
